apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <BASE64_CERTIFICATE>
    server: https://your-cluster-url.com:6443
  name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-user
  name: my-context
current-context: my-context
kind: Config
preferences: {}
users:
- name: my-user
  user:
    client-certificate-data: <BASE64_CERTIFICATE>
    client-key-data: <BASE64_KEY>
