name: Deploy to Kubernetes

on:
  push:
    branches:
      - main   # Trigger deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.jaspreetsingh9102000@gmail.com}}   # Use the secret for Docker username
          password: ${{ secrets.groupprojectdeveops }}   # Use the secret for Docker password

      - name: Build Docker Image
        run: |
          docker build -t jass123saini/myapp:latest .

      - name: Push Docker Image
        run: |
          docker push jass123saini/myapp:latest  # Push to the same image name you built

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/myapp-deployment
          kubectl get pods
          kubectl get services
