name: Deploy to Kubernetes

on:
  push:
    branches:
      - main   # Trigger deployment on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}   # Use the secret for Docker username
          password: ${{ secrets.DOCKER_PASSWORD }}   # Use the secret for Docker password

      - name: Build Docker Image
        run: |
          docker build -t jass123saini/myapp:latest .

      - name: Push Docker Image
        run: |
          docker push jass123saini/myapp:latest  # Push to the same image name you built

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Ensure the .kube directory exists
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/myapp-deployment
          kubectl get pods
          kubectl get services
