name: Deploy to Kubernetes

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Registry
    - name: Log in to Docker Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build -t jass123saini/your-app:latest .
        docker push jass123saini/your-app:latest

    # Step 4: Set up kubectl
    - name: Set up kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config

    # Step 5: Deploy to Kubernetes
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f configmap.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f hpa.yaml

    # Step 6: Verify Deployment
    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/my-app
        kubectl get pods
        kubectl get svc
