name: Build, Push, and Deploy Dockerized Application with Kubernetes

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Cache Docker layers to speed up builds
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # Step 4: Log in to Docker Hub (Replace with your Docker registry if necessary)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Store your Docker Hub username as a secret
          password: ${{ secrets.DOCKER_PASSWORD }}  # Store your Docker Hub password as a secret

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t yourusername/my-app:${{ github.sha }} .

      # Step 6: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: |
          docker push yourusername/my-app:${{ github.sha }}

      # Step 7: Set up Kubernetes CLI (kubectl) using the correct version
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v1  # Corrected version

      # Step 8: Set up Kubeconfig (Authenticate to your Kubernetes Cluster)
      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.K8S_KUBECONFIG }}" > ~/.kube/config

      # Step 9: Apply Kubernetes manifests (without ConfigMap and HPA)
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
