name: Kubernetes Deployment

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up kubectl and kubeconfig
    - name: Set up kubectl
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENT }}" > ~/.kube/config
        chmod 600 ~/.kube/config

    # Step 3: Verify Kubernetes cluster access
    - name: Verify Kubernetes Access
      run: |
        kubectl version --client
        kubectl config view
        kubectl get nodes

    # Step 4: Deploy Kubernetes Configurations
    - name: Apply Kubernetes Manifests
      run: |
        kubectl apply -f configmap.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl apply -f hpa.yaml

    # Step 5: Verify Deployment
    - name: Verify Pods and Services
      run: |
        kubectl get pods
        kubectl get services
